-- CreateEnum
CREATE TYPE "Category" AS ENUM ('TRUE_CRIME', 'COMEDY', 'NEWS', 'EDUCATION', 'TECHNOLOGY', 'SPORTS', 'HEALTH', 'BUSINESS', 'HISTORY', 'FICTION', 'STORYTELLING', 'SELF_IMPROVEMENT', 'POLITICS', 'MUSIC', 'SCIENCE', 'PHILOSOPHY', 'TRAVEL', 'LANGUAGE', 'CULTURE', 'RELIGION', 'ART', 'KIDS', 'ENVIRONMENT', 'ANIME', 'GAMING', 'FINANCE', 'LITERATURE', 'RELATIONSHIPS', 'FOOD', 'DOCUMENTARY', 'ENTERTAINMENT', 'INTERVIEWS');

-- AlterTable
ALTER TABLE "Episode" ADD COLUMN     "category" "Category"[] DEFAULT ARRAY[]::"Category"[];
